# Generated by Django 3.2.9 on 2021-12-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='correctly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version',
            name='npp',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
