# Generated by Django 3.2.9 on 2021-12-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_auto_20211201_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='numtask',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='version',
            name='npp',
            field=models.IntegerField(default=0),
        ),
    ]
