# Generated by Django 3.2.9 on 2021-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0004_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(max_length=5),
        ),
    ]
