# Generated by Django 3.2.9 on 2021-12-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0005_alter_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='task',
        ),
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='math_app.task'),
            preserve_default=False,
        ),
    ]
