# Generated by Django 3.2.9 on 2021-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0007_alter_lesson_correctly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='correctly',
            field=models.CharField(default='не проверено', max_length=13),
        ),
    ]
